### ISSUE TITLE
引数つきのAPIが使えない

### ISSUE THREAD

**Issue by mzp** [increments/qiita-rb#12]
例えば以下のようなコードを実行するとエラーが発生します。

```ruby
require 'qiita'

client = Qiita::Client.new(access_token: 'some access token')
client.get_user("mzp")
```

```shell
/Users/mzp/git/qiita-rb/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/utils.rb:129:in `update': undefined method `each' for "mzp":String (NoMethodError)
        from /Users/mzp/git/qiita-rb/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:141:in `block in get'
        from /Users/mzp/git/qiita-rb/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:374:in `block in run_request'
        from /Users/mzp/git/qiita-rb/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:388:in `block in build_request'
        from /Users/mzp/git/qiita-rb/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/request.rb:26:in `block in create'
        from /Users/mzp/git/qiita-rb/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/request.rb:25:in `tap'
        from /Users/mzp/git/qiita-rb/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/request.rb:25:in `create'
        from /Users/mzp/git/qiita-rb/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:384:in `build_request'
        from /Users/mzp/git/qiita-rb/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:370:in `run_request'
        from /Users/mzp/git/qiita-rb/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
        from /Users/mzp/git/qiita-rb/lib/qiita/client.rb:153:in `process'
        from /Users/mzp/git/qiita-rb/lib/qiita/client.rb:55:in `get'
        from /Users/mzp/git/qiita-rb/lib/qiita/resource_based_methods.rb:336:in `get_user'
        from foo.rb:6:in `<main>'
```

おそらく https://github.com/increments/qiita-rb/commit/5488fe0bedf7f3e86063fee7e6330dec07197924 で文字列補完がなくなっているのが原因です。

**Comment by r7kamura** [comment]
@mzp ありがとうございます! 修正して v1.3.1 をリリースしました :bow:

**Comment by mzp** [comment]
ありがとうございます! :ok_woman:
